version: "3.3"
services:
  viyaapp:
      build: .
      restart: always
      ports:
        - 8080:8080
      environment:
        - VIYA_SERVER=http://kdk2017.fbi.sashq-d.openstack.sas.com
        - DEBUG=logout,user,cookie,bell,loc

