version: "3.3"
services:
  viyaapp:
      build: .
      restart: always
      ports:
        - 8080:8080
      environment:
        - VIYA_SERVER=
        - COOKIE=None,false
        - DEBUG=logout,user,cookie,bell,loc

