version: "3.3"
services:
  myapi:
      build: .
      restart: always
      ports:
        - 8080:8080
      environment:
        - VIYA_SERVER=
        - CLIENTID=myapi
        - CLIENTSECRET=secret



